version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb:dgrow"
    ports:
      - "8080:8081"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/mytb-data:/data
      - ~/mytb-logs:/var/log/thingsboard